name: Multi-Platform Build & Package

on:
  push:
    branches: [ "2.X" ]
  pull_request:
    branches: [ "2.X" ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.6.0'
          arch: 'win64_msvc2019_64'

      - name: Configure CMake
        run: |
          cmake -S . -B build `
          -DCMAKE_BUILD_TYPE=Release `
          -DCMAKE_PREFIX_PATH="${{ env.Qt6_DIR }}"

      - name: Build & Package
        run: |
          cmake --build build --config Release
          cd build
          cpack -C Release

      - name: Upload Artifacts (Installer + Portable)
        uses: actions/upload-artifact@v4
        with:
          name: GVD-Windows-Packages
          path: |
            build/GUI-Video-Downloader-1.0.0-win64.exe
            build/GUI-Video-Downloader-1.0.0-win64.zip
            build/Release/App.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-dev libxkbcommon-x11-0 binutils

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.6.0'

      - name: Build & Package
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release
          cd build
          cpack -C Release

      - name: Upload Artifacts (Installer + Portable)
        uses: actions/upload-artifact@v4
        with:
          name: GVD-Linux-Packages
          path: |
            build/*.deb
            build/*.tar.gz
            build/App

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.6.0'

      - name: Build & Package
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release
          cd build
          cpack -C Release

      - name: Upload Artifacts (Installer + Portable)
        uses: actions/upload-artifact@v4
        with:
          name: GVD-MacOS-Packages
          path: |
            build/*.dmg
            build/*.zip
            build/App.app/Contents/MacOS/App